version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3307:3306" # Host port mapping for external access
    networks:
      - app-network

  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tododb
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
